### ISSUE TITLE
Add plugin system

### ISSUE THREAD

**Issue by szastupov** [szastupov/aiotg#30]
We need a plugin system that allows to define new bot commands and handlers in separate modules. It would also be nice to be able enable/disable plugins without reloading the bot.

**Comment by bliz937** [comment]
My approach is:

Have the main Bot instance in ```main.py```, where here we have 2 things happen.
1. act as the modules listing, or main menu
2. Get and send off updates to relevant modules.

```main.py``` loads the modules from a specified directory, and each module having its own Bot instance.
When loading the modules, set the API key, name, etc in the module's Bot instance.
Each module has its own entry command, and this gets copied to a command array. Once all the modules are loaded, prepend the command array to each module Bot instance - the ```_commands``` variable.

Extract and modify the following methods from ```bot.py``` and put them in ```main.py```:
```loop``` and ```_process_updates```.

Extract ```loop``` so that we call this function in ```main.py``` and not the Bot instance in ```main.py```.
Extract and modify ```_process_updates``` to set the ```_offset``` and pass the update to the relevant module.

Then from a user point of view, message the bot. 
First the Bot in ```main.py``` will process the message, since the user hasn't entered a module, and display a list of installed modules. Once a user goes into a module, each subsequent request from that user gets passed into the ```_process_updates``` of the module's Bot instance.

This is a rough approach of my implementation.

**Comment by szastupov** [comment]
To be honest I was thinking about something simpler. There is [Errbot](http://errbot.io/en/latest/) and I don't want to compete with them.

So my first goal is to let users create reusable commands, something like this (just a draft, not a final API):

```python
from aiotg import plugin

@plugin.command(r"/echo (.+)")
def echo(bot, chat, match):
    return chat.reply(match.group(1))
```

Then users can can import specific module and it will register itself. We can add optional autoloading from a folder as well. Note that I would like to keep namespace global and not impose any naming convention.

Enabling disabling modules from bot is another goal, but I'd rather implement it as bot API and then create a text interface as a "plugin manager" plugin.

**Comment by szastupov** [comment]
Hmmm, what if we clone the blueprints system from flask? 🤔

**Comment by derfenix** [comment]
I think it is not a good idea. Your library is a flat and clean async binding for Telegram's API and should stay so. Plugins is the application's responsibility area, not library's. 
That's just my opinion :smile:
